### ISSUE TITLE
Update http://wiki.mate-desktop.org/replace_unity_by_mate for Ubuntu 17.04

### ISSUE THREAD

**Issue by krichter722** [mate-desktop/mate-user-guide#1]
The instructions at http://wiki.mate-desktop.org/replace_unity_by_mate don't work smoothly with Ubuntu 17.04 because

  * the packages `mate-media-gstreamer` and `mate-archive-keyring` aren't available
  * the command `lightdm-set-defaults` fails due to `sudo: /usr/lib/lightdm/lightdm-set-defaults: command not found`

I hope this is the right place to report this. [The mailing list inscription site](http://ml.mate-desktop.org/listinfo/) is not reachable, so I couldn't make sure.

**Comment by monsta** [comment]
The wiki isn't in `mate-user-guide` package for sure... we have https://github.com/mate-desktop/mate-desktop.org though.

Well, that page is horribly outdated. It's written in 2014, so it's about MATE 1.8 and Ubuntu MATE 14.04/14.10, both of which are EOL by now. People that worked on that page don't contribute anymore.

You can ask at https://ubuntu-mate.community, maybe someone could provide some instructions for the modern releases.
