### ISSUE TITLE
External URLs point to non-existent pages

### ISSUE THREAD

**Issue by rbuj** [mate-desktop/mate-user-guide#11]
https://github.com/mate-desktop/mate-user-guide/blob/8329f38401fe7695ddcab39e89e022620fca15f6/mate-user-guide/C/gosfeedback.xml#L83

https://github.com/mate-desktop/mate-user-guide/blob/8329f38401fe7695ddcab39e89e022620fca15f6/mate-user-guide/C/gosfeedback.xml#L72

https://github.com/mate-desktop/mate-user-guide/blob/8329f38401fe7695ddcab39e89e022620fca15f6/mate-user-guide/C/gostools.xml#L1049

**Comment by raveit65** [comment]
We dropped the mailing list a while ago, so these links can be removed.
Not sure how we can replace the the gnome live link.
@flexiondotorg 
Any idea?

**Comment by monsta** [comment]
I think it can be removed too. I don't know what "joining" meant in GNOME, but it doesn't look relevant for us. All contributors can simply make pull requests, the only joining that's needed is a GitHub account.
