### ISSUE TITLE
mateversion entity has not been updated for a while, manrevision is not currently used

### ISSUE THREAD

**Issue by rbuj** [mate-desktop/mate-user-guide#16]
https://github.com/mate-desktop/mate-user-guide/blob/4910cce135adea22e92f9070830792250014a008/mate-user-guide/C/index.docbook#L4

https://github.com/mate-desktop/mate-user-guide/blob/4910cce135adea22e92f9070830792250014a008/mate-user-guide/C/index.docbook#L5

**Comment by raveit65** [comment]
omg :)

**Comment by raveit65** [comment]
Ok, i think it make sense to update `manrevision` when all your changes are done and before we make a new release.

**Comment by rbuj** [comment]
@raveit65 
You're doing an extraordinary job.

**Comment by monsta** [comment]
I see that the first variable is used in that document, but I can't find it anywhere when looking at the guide via Yelp...
```xml
    <releaseinfo>This manual describes version &mateversion; of the
    MATE desktop.</releaseinfo>
```
