### ISSUE TITLE
Mailing list is down

### ISSUE THREAD

**Issue by MagicFab** [mate-desktop/mate-user-guide#2]
The mate-user-guide README mentions the mailing list as a means to join/communicate with the project, at https://github.com/mate-desktop/mate-user-guide/blob/master/README

It seems the link is down:
http://ml.mate-desktop.org/listinfo/

**Comment by monsta** [comment]
Link removed: https://github.com/mate-desktop/mate-user-guide/commit/78767818479b5596b9a7dd07665f6ce9f3473d28

Mailing list won't be restored: https://github.com/mate-desktop/mate-desktop.org/issues/76
