### ISSUE TITLE
1.23.0: itstool is core dumping

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/mate-user-guide#38]
This is not strictly mate-user-guide related issue but simple I'm looking for some help.

During build mate-user-guide python used by itstool is core dumping and on first look looks like it maybe some issue with libxml2 python loadable module.
Do you know anything about such issue?

<pre>/bin/sh: line 3: 15569 Segmentation fault      (core dumped) itstool -m &quot;${mo}&quot; ${d}/C/index.docbook ${d}/C/legal.xml ${d}/C/gosbasic.xml ${d}/C/goscustdesk.xml ${d}/C/g</pre>

<pre>[tkloczko@barrel ~]$ coredumpctl list | tail -n 1
Sat 2019-07-06 13:52:08 BST   15569  1000  1000  11 present   /usr/bin/python3.7
</pre>
<pre>[tkloczko@barrel ~]$ coredumpctl gdb 15569
           PID: <b>15569</b> (itstool)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 11 (SEGV)
     Timestamp: Sat 2019-07-06 13:52:08 BST (3min 11s ago)
  Command Line: /usr/bin/python3 -s /usr/bin/itstool -m ../ru/ru.mo ..//C/index.docbook ..//C/legal.xml ..//C/gosbasic.xml ..//C/goscustdesk.xml ..//C/goseditmainmenu.xml ..//C/goscaja.xml ..//C/gosoverview.xml ..//C/gospanel.xml ..//C/gosstartsession.xml ..//C/gostools.xml ..//C/gosdconf.xml ..//C/gosdconfkeys.xml ..//C/gosfeedback.xml ..//C/glossary.xml
    Executable: <b>/usr/bin/python3.7</b>
 Control Group: /user.slice/user-1000.slice/session-39.scope
          Unit: session-39.scope
         Slice: user-1000.slice
       Session: 39
     Owner UID: 1000 (tkloczko)
       Boot ID: 9ab00058f1414c4ea9a34cb8b5268843
    Machine ID: 0594d5138b9d4b6fafc8fd1fb24e12d2
      Hostname: barrel
       Storage: /var/lib/systemd/coredump/core.itstool.1000.9ab00058f1414c4ea9a34cb8b5268843.15569.1562417528000000.lz4
       Message: Process 15569 (itstool) of user 1000 dumped core.
                
                Stack trace of thread 15569:
                #0  0x00007fcea96ddba3 _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                #1  0x00007fce9bf1afe3 libxml_xmlErrorFuncHandler (libxml2mod.so)
                #2  0x00007fce9bab7374 xmlParserPrintFileContextInternal (libxml2.so.2)
                #3  0x00007fce9bab84ee xmlReportError (libxml2.so.2)
                #4  0x00007fce9babc2ab __xmlRaiseError (libxml2.so.2)
                #5  0x00007fce9babc645 xmlNsErr.lto_priv.0 (libxml2.so.2)
                #6  0x00007fce9bab2acf xmlParseStartTag2.lto_priv.0 (libxml2.so.2)
                #7  0x00007fce9baacaaf xmlParseElement (libxml2.so.2)
                #8  0x00007fce9baabf95 xmlParseContent (libxml2.so.2)
                #9  0x00007fce9baac9c1 xmlParseElement (libxml2.so.2)
                #10 0x00007fce9baad0d2 xmlParseDocument (libxml2.so.2)
                #11 0x00007fce9bf12932 libxml_xmlParseDocument (libxml2mod.so)
                #12 0x00007fcea96bc44e _PyMethodDef_RawFastCallKeywords (libpython3.7m.so.1.0)
                #13 0x00007fcea96bc583 _PyCFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #14 0x00007fcea96eedb3 call_function (libpython3.7m.so.1.0)
                #15 0x00007fcea972a1b2 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #16 0x00007fcea96dd592 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #17 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #18 0x00007fcea97257ee _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #19 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #20 0x00007fcea96dd732 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #21 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #22 0x00007fcea9726518 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #23 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #24 0x00007fcea96dd732 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #25 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #26 0x00007fcea9726518 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #27 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #28 0x00007fcea96dd732 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #29 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #30 0x00007fcea9726518 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #31 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #32 0x00007fcea96dd732 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #33 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #34 0x00007fcea9726518 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #35 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #36 0x00007fcea96dd732 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #37 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #38 0x00007fcea9726518 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #39 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #40 0x00007fcea96dd732 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                #41 0x00007fcea96eec9f call_function (libpython3.7m.so.1.0)
                #42 0x00007fcea9726518 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                #43 0x00007fcea96dc730 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                #44 0x00007fcea96dd489 PyEval_EvalCodeEx (libpython3.7m.so.1.0)
                #45 0x00007fcea976bf1b PyEval_EvalCode (libpython3.7m.so.1.0)
                #46 0x00007fcea97acef3 run_mod (libpython3.7m.so.1.0)
                #47 0x00007fcea97ad447 PyRun_FileExFlags (libpython3.7m.so.1.0)
                #48 0x00007fcea97b393a PyRun_SimpleFileExFlags (libpython3.7m.so.1.0)
                #49 0x00007fcea97b56c1 pymain_main (libpython3.7m.so.1.0)
                #50 0x00007fcea97b586c _Py_UnixMain (libpython3.7m.so.1.0)
                #51 0x00007fcea9920193 __libc_start_main (libc.so.6)
                #52 0x000056176109d08e _start (python3.7)

<font color="#75507B"><b>GNU gdb (GDB) Fedora 8.3.50.20190702-19.fc31</b></font>
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type &quot;show copying&quot; and &quot;show warranty&quot; for details.
This GDB was configured as &quot;x86_64-redhat-linux-gnu&quot;.
Type &quot;show configuration&quot; for configuration details.
For bug reporting instructions, please see:
&lt;http://www.gnu.org/software/gdb/bugs/&gt;.
Find the GDB manual and other documentation resources online at:
    &lt;http://www.gnu.org/software/gdb/documentation/&gt;.

For help, type &quot;help&quot;.
Type &quot;apropos word&quot; to search for commands related to &quot;word&quot;...
Reading symbols from <font color="#4E9A06">/usr/bin/python3.7</font>...
Reading symbols from <font color="#4E9A06">.gnu_debugdata for /usr/bin/python3.7</font>...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.7)

warning: core file may not match specified executable file.
[New LWP 15569]
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/lib64/libthread_db.so.1&quot;.
Core was generated by `/usr/bin/python3 -s /usr/bin/itstool -m ../ru/ru.mo ..//C/index.docbook ..//C/l&apos;.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  <font color="#3465A4">0x00007fcea96ddba3</font> in <font color="#C4A000">_PyFunction_FastCallDict</font> () from /lib64/libpython3.7m.so.1.0
Missing separate debuginfos, use: dnf debuginfo-install python3-3.7.4~rc2-1.fc31.x86_64
(gdb) bt full
#0  <font color="#3465A4">0x00007fcea96ddba3</font> in <font color="#C4A000">_PyFunction_FastCallDict</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#1  <font color="#3465A4">0x00007fce9bf1afe3</font> in <font color="#C4A000">libxml_xmlErrorFuncHandler</font> () from /usr/lib64/python3.7/site-packages/libxml2mod.so
No symbol table info available.
#2  <font color="#3465A4">0x00007fce9bab7374</font> in <font color="#C4A000">xmlParserPrintFileContextInternal</font> () from /lib64/libxml2.so.2
No symbol table info available.
#3  <font color="#3465A4">0x00007fce9bab84ee</font> in <font color="#C4A000">xmlReportError</font> () from /lib64/libxml2.so.2
No symbol table info available.
#4  <font color="#3465A4">0x00007fce9babc2ab</font> in <font color="#C4A000">__xmlRaiseError</font> () from /lib64/libxml2.so.2
No symbol table info available.
#5  <font color="#3465A4">0x00007fce9babc645</font> in <font color="#C4A000">xmlNsErr.lto_priv.0</font> () from /lib64/libxml2.so.2
No symbol table info available.
#6  <font color="#3465A4">0x00007fce9bab2acf</font> in <font color="#C4A000">xmlParseStartTag2.lto_priv.0</font> () from /lib64/libxml2.so.2
No symbol table info available.
#7  <font color="#3465A4">0x00007fce9baacaaf</font> in <font color="#C4A000">xmlParseElement</font> () from /lib64/libxml2.so.2
No symbol table info available.
#8  <font color="#3465A4">0x00007fce9baabf95</font> in <font color="#C4A000">xmlParseContent</font> () from /lib64/libxml2.so.2
No symbol table info available.
#9  <font color="#3465A4">0x00007fce9baac9c1</font> in <font color="#C4A000">xmlParseElement</font> () from /lib64/libxml2.so.2
No symbol table info available.
#10 <font color="#3465A4">0x00007fce9baad0d2</font> in <font color="#C4A000">xmlParseDocument</font> () from /lib64/libxml2.so.2
No symbol table info available.
#11 <font color="#3465A4">0x00007fce9bf12932</font> in <font color="#C4A000">libxml_xmlParseDocument</font> () from /usr/lib64/python3.7/site-packages/libxml2mod.so
No symbol table info available.
#12 <font color="#3465A4">0x00007fcea96bc44e</font> in <font color="#C4A000">_PyMethodDef_RawFastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#13 <font color="#3465A4">0x00007fcea96bc583</font> in <font color="#C4A000">_PyCFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#14 <font color="#3465A4">0x00007fcea96eedb3</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#15 <font color="#3465A4">0x00007fcea972a1b2</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#16 <font color="#3465A4">0x00007fcea96dd592</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
No symbol table info available.
#17 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#18 <font color="#3465A4">0x00007fcea97257ee</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#19 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#20 <font color="#3465A4">0x00007fcea96dd732</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#21 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#22 <font color="#3465A4">0x00007fcea9726518</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#23 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#24 <font color="#3465A4">0x00007fcea96dd732</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#25 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#26 <font color="#3465A4">0x00007fcea9726518</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#27 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#28 <font color="#3465A4">0x00007fcea96dd732</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#29 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#30 <font color="#3465A4">0x00007fcea9726518</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#31 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#32 <font color="#3465A4">0x00007fcea96dd732</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
#33 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#34 <font color="#3465A4">0x00007fcea9726518</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#35 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#36 <font color="#3465A4">0x00007fcea96dd732</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#37 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#38 <font color="#3465A4">0x00007fcea9726518</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#39 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#40 <font color="#3465A4">0x00007fcea96dd732</font> in <font color="#C4A000">_PyFunction_FastCallKeywords</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#41 <font color="#3465A4">0x00007fcea96eec9f</font> in <font color="#C4A000">call_function</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#42 <font color="#3465A4">0x00007fcea9726518</font> in <font color="#C4A000">_PyEval_EvalFrameDefault</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#43 <font color="#3465A4">0x00007fcea96dc730</font> in <font color="#C4A000">_PyEval_EvalCodeWithName</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#44 <font color="#3465A4">0x00007fcea96dd489</font> in <font color="#C4A000">PyEval_EvalCodeEx</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#45 <font color="#3465A4">0x00007fcea976bf1b</font> in <font color="#C4A000">PyEval_EvalCode</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#46 <font color="#3465A4">0x00007fcea97acef3</font> in <font color="#C4A000">run_mod</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#47 <font color="#3465A4">0x00007fcea97ad447</font> in <font color="#C4A000">PyRun_FileExFlags</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#48 <font color="#3465A4">0x00007fcea97b393a</font> in <font color="#C4A000">PyRun_SimpleFileExFlags</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#49 <font color="#3465A4">0x00007fcea97b56c1</font> in <font color="#C4A000">pymain_main</font> () from /lib64/libpython3.7m.so.1.0
--Type &lt;RET&gt; for more, q to quit, c to continue without paging--
No symbol table info available.
#50 <font color="#3465A4">0x00007fcea97b586c</font> in <font color="#C4A000">_Py_UnixMain</font> () from /lib64/libpython3.7m.so.1.0
No symbol table info available.
#51 <font color="#3465A4">0x00007fcea9920193</font> in <font color="#C4A000">__libc_start_main</font> () from /lib64/libc.so.6
No symbol table info available.
#52 <font color="#3465A4">0x000056176109d08e</font> in <font color="#C4A000">_start</font> ()
No symbol table info available.
</pre>

**Comment by raveit65** [comment]
MATE 1.23 for fedora 
https://copr.fedorainfracloud.org/coprs/raveit65/MATE-1.23.x/

**Comment by kloczek** [comment]
And if you will check https://copr.fedorainfracloud.org/coprs/raveit65/MATE-1.23.x/packages/ you can find that no one tested build mate-user-guide.
So again: do you know anything about some python libxml2 module issue?

**Comment by raveit65** [comment]
Really?
https://copr.fedorainfracloud.org/coprs/raveit65/MATE-1.23.x/build/962656/

**Comment by kloczek** [comment]
That was really helpful ..
