### ISSUE TITLE
Help for several application is broken with m-u-g

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-user-guide#5]
ie. mate-panel:
Click on a help button an you will see that the links don't exists.
This happens at several points.
A look at the code shows me that non page for mate- panel exists.
Honestly, we should revert using mate-user-guide for applications if nobody is there to implement the pages.

**Comment by NiceandGently** [comment]
more apps:
- mate-screenshoot

**Comment by monsta** [comment]
There's no help for mate-panel in m-u-g at all, so I can't put the correct help links into mate-panel code.

**Comment by NiceandGently** [comment]
With mate-1.8 all is in mate-desktop, but *.xml files
```
mate-desktop-libs-1.8.2-2.fc20.x86_64 : Shared libraries for libmate-desktop
Quelle      : @updates
Übereinstimmung von:
Dateiname     : /usr/share/help/C/mate-user-guide/gospanel.xml

mate-desktop-libs-1.8.2-2.fc20.x86_64 : Shared libraries for libmate-desktop
Quelle      : @updates
Übereinstimmung von:
Dateiname     : /usr/share/help/de/mate-user-guide/gospanel.xml

mate-desktop-1.8.2-2.fc20.x86_64 : Shared code for mate-panel, mate-session,
                                 : mate-file-manager, etc
Quelle      : @updates
Übereinstimmung von:
Dateiname     : /usr/share/help/ru/mate-user-guide/gospanel.xml


etc.
```

**Comment by monsta** [comment]
And all that has been removed in 1.10...

**Comment by NiceandGently** [comment]
@monsta 
I have a idea :)
I want to try to include the gospanel.xml from m-d-1.8.2 in mate-panel.
But for this the help link in panel have to changed.
»help:mate-user-guide«  to »help:mate-panel«
Where can i do that in panel code to test my thoughts locally?

**Comment by NiceandGently** [comment]
@monsta 
ok, i found the code lines in mate-panel.
And i have a working help for mate-panel again :)

**Comment by infirit** [comment]
Why the unnecessary duplication of effort? Motohos documented thing thoroughly on the wiki, http://wiki.mate-desktop.org/dev-doc:doc-team-guide

**Comment by NiceandGently** [comment]
@infirit 
Hey nice to hear something from you.
The question is ' who want to do the work'?
you?
motohoss?
stefano?

**Comment by NiceandGently** [comment]
mate-screenshoot is fixed
https://github.com/mate-desktop/mate-utils/commit/c9774ca4895f6b9837ba7ca3783d5cd3596a36fc

**Comment by NiceandGently** [comment]
fix with docbook guide
